version: "3"

dotenv: [".env"]

tasks:
  build:
    cmds:
      - task: buildJar
      - task: buildImage
  buildJar:
    cmds:
      - mvn -Pnative -DskipTests package
  buildImage:
    cmds:
      - docker build -t cappuccino:$CAP_VERSION .
  run:
    cmds:
      - kubectl apply -f k8s/cappuccino-deployment.yml
  stop:
    cmds:
      - kubectl delete -f k8s/cappuccino-deployment.yml
