apiVersion: apps/v1
kind: Deployment
metadata:
  name: cappuccino
spec:
  selector:
    matchLabels:
      app: cappuccino
  template:
    metadata:
      labels:
        app: cappuccino
    spec:
      containers:
        - name: cappuccino
          image: cappuccino:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
